# Generated by Django 5.1.1 on 2024-10-05 11:05

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcoming_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_image/')),
                ('title', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('event_datetime', models.DateTimeField(validators=[blog.models.validate_future_datetime])),
            ],
        ),
    ]
