# Generated by Django 5.1.1 on 2024-10-05 01:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_teacher_course_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='account',
            field=models.ManyToManyField(blank=True, null=True, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
    ]
