# Generated by Django 5.1.1 on 2024-10-05 01:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='account',
            field=models.ManyToManyField(blank=True, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
    ]
